BAI 1:

SELECT THOIGIAN+CAST(PHANCONG.THOIGIAN AS decimal(6,2))
  FROM PHANCONG
  
  GO
  SELECT THOIGIAN + CONVERT(decimal(6,2),101)
  FROM PHANCONG
 
  go

  SELECT THOIGIAN+CAST(PHANCONG.THOIGIAN AS VARCHAR)
  FROM PHANCONG
  
  GO
  SELECT THOIGIAN + CONVERT(VARCHAR,101)
  FROM PHANCONG
GO
SELECT TENPHG,CAST(AVG(LUONG) AS decimal(10,2))AS LUONGTRUNGBINH
FROM PHONGBAN,NHANVIEN 
WHERE maphg=PHG
GROUP BY TENPHG
GO

Select TENPHG, left(cast (AVG(LUONG) as varchar(10)),3)+','
+replace(cast(AVG(LUONG) as varchar(10)),left(cast(AVG(LUONG) as varchar(10)),3),',')
as 'luong trung binh' from NHANVIEN
inner join PHONGBAN on NHANVIEN.PHG=PHONGBAN.MAPHG
group by TENPHG


BAI 2:

SELECT THOIGIAN as Tổngthờigian, ceiling(CAST(PHANCONG.THOIGIAN AS decimal(6,2)))
  FROM PHANCONG, DEAN

  GO
  SELECT THOIGIAN as Tổngthờigian, floor(CAST(PHANCONG.THOIGIAN AS decimal(6,2)))
  FROM PHANCONG, DEAN

  GO
  SELECT HONV+' '+TENLOT+' '+TENNV, LUONG FROM NHANVIEN
  WHERE LUONG > (SELECT ROUND(AVG(luong),2) FROM NHANVIEN WHERE PHG=(SELECT MAPHG FROM PHONGBAN WHERE TENPHG = N'Nghiên cứu'))

  BAI 3:


SELECT UPPER(HONV) AS 'HO NV', TENLOT, TENNV, DCHI, COUNT(MA_NVIEN) AS 'SO THAN NHAN' FROM NHANVIEN
INNER JOIN THANNHAN  ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
GROUP BY HONV, TENLOT, TENNV, DCHI
HAVING COUNT(MA_NVIEN) >=2


SELECT HONV, LOWER(TENNV) AS 'TEN LOT', TENNV, DCHI, COUNT(MA_NVIEN) AS 'SO THAN NHAN' FROM NHANVIEN
INNER JOIN THANNHAN  ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
GROUP BY HONV, TENLOT, TENNV, DCHI
HAVING COUNT(MA_NVIEN) >=2


SELECT 
LOWER(LEFT(TENNV,1)) + UPPER(SUBSTRING(TENNV,2,1)) + SUBSTRING(TENNV,3,LEN(TENNV)-2),
COUNT(MA_NVIEN) AS 'SO THAN NHAN' FROM NHANVIEN
INNER JOIN THANNHAN  ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
GROUP BY HONV, TENLOT, TENNV, DCHI
HAVING COUNT(MA_NVIEN) >=2


SELECT DCHI,LEFT(DCHI,CHARINDEX(' ',DCHI)) AS 'SO NHA' FROM NHANVIEN
SELECT DCHI,SUBSTRING(DCHI,CHARINDEX(',',DCHI),9) AS 'THANH PHO' FROM NHANVIEN
SELECT DCHI,SUBSTRING(DCHI,CHARINDEX(' ',DCHI),CHARINDEX(',',DCHI) - 3) AS 'TEN DUONG' FROM NHANVIEN


SELECT TENPHG,TRPHG,B.TENNV, COUNT(A.MANV) AS 'SOLUONG'
FROM NHANVIEN A 
INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = A.PHG
INNER JOIN NHANVIEN B ON  B.MANV = PHONGBAN.TRPHG
GROUP BY TENPHG, TRPHG, B.TENNV

BAI 4:

SELECT * FROM NHANVIEN 
WHERE YEAR(NGSINH) >=196 AND YEAR(NGSINH) <= 1965


SELECT *, YEAR(GETDATE()) - YEAR(NGSINH) AS 'TUOI' FROM NHANVIEN


SELECT *,DATENAME(WEEKDAY,NGSINH) AS 'THU' FROM NHANVIEN


SELECT TENPHG, TRPHG, B.TENNV, NG_NHANCHUC, COUNT(A.MANV) AS 'SO LUONG NV', 
CONVERT(VARCHAR, NG_NHANCHUC , 105) AS 'NGAY NHAN CHUC'
FROM NHANVIEN A
INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = A.PHG
INNER JOIN NHANVIEN B ON B.MANV = PHONGBAN.TRPHG
GROUP BY TENPHG, TRPHG, NG_NHANCHUC,B.TENNV